'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Path_Structure_Maintenance.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to function DrawPoints(arr, color) {
        '''    var stats = GetStandardDeviation(arr);
        '''    var clr = &quot;black&quot;;
        '''    if (color != undefined) { clr = color; }
        '''    var canv = document.getElementById(&quot;canvGraph&quot;);
        '''    var ctx = canv.getContext(&apos;2d&apos;);
        '''    ctx.save();
        '''    ctx.strokeStyle = clr;
        '''    ctx.fillStyle = clr;
        '''    var ratioX, ratioY, sampleX, maxValue, minValue;
        '''    for (var len = arr.length, n = 0; n &lt; len; n++) {
        '''        // Verify that the value is within the standard deviation
        '''        if (arr[n] &lt; (st [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DrawGraph() As String
            Get
                Return ResourceManager.GetString("DrawGraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''	&lt;script src=&apos;https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js&apos;&gt;&lt;/script&gt;&lt;link href=&apos;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css&apos; rel=&apos;stylesheet&apos; integrity=&apos;sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==&apos; crossorigin=&apos;anonymous&apos;/&gt;&lt;script type=&apos;text/javascript&apos; src=&apos;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js&apos; integrity=&apos;sha256-KXn5puM [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FileSystemVisualAuditTemplate() As String
            Get
                Return ResourceManager.GetString("FileSystemVisualAuditTemplate", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
